### ISSUE TITLE
analyse: schéma réseau

### ISSUE THREAD

**Issue by greut** [HE-Arc/Extrusion---web-interface#1]
**Idée à prendre ou à laisser**

Dans votre phase d'analyse, je verrai bien des schémas réseaux correspondant à l'installation physique, ainsi que des analyses au niveau des diverses contraintes physique en jeu.

Le but pouvant être de justifier des choix techniques ultérieurs.

**Comment by lewisjaggi** [comment]
https://github.com/HE-Arc/Extrusion---web-interface/wiki/Documentation-R%C3%A9seau

**Comment by greut** [comment]
>  analyses au niveau des diverses contraintes physique

Des calculs de bande-passante me semblent judicieux.
