### ISSUE TITLE
analyse: linéarisation, pliage, visualisation

### ISSUE THREAD

**Issue by greut** [HE-Arc/Extrusion---web-interface#2]
**Idée à prendre ou à laisser**

Le schéma réseau des LEDs risque de ressembler à un arbre, ou un tas de grapes, qu'il est possible de linéariser (aka numéroter de 1 à 8000). Voir même de représenter ces valeurs sur la structure physique à l'aide d'un arc-en-ciel de couleurs (cf. https://bost.ocks.org/mike/algorithms/)

Le pliage, le passage d'une dimension N vers une dimension N+1. Par exemple, les adresses IPv4, un monde linéaire, peuvent être placées sur une courbe de Hilbert et ainsi s'afficher en 2D (cf https://www.xkcd.com/195/). La pliage qui vous a été fournit n'en est qu'un parmi tout un tas d'autres. Je pense qu'il serait intéressant d'explorer le pliage fournit ainsi que tous les autres que vous jugerai intéressants. Ces pliages 2D -> 3D et/ou 1D -> 3D peuvent aider à fournit une métaphore dans l'interaction avec le dit cube. Notre propre planètre offre des cas intéressants de 3D -> 2D, https://github.com/d3/d3-geo-projection/

**Comment by lewisjaggi** [comment]
https://github.com/HE-Arc/Extrusion---web-interface/wiki/D%C3%A9pliage--et-Syst%C3%A8mes-de-coordonn%C3%A9es

**Comment by greut** [comment]
> Pour ce système de coordonnées on divise le cube par face numérotée. Chaque face possède son propre système de coordonnées (x,y) pour trouvé un carré de ledstrips. Pour chaque carré de lesdstrips on numérote les arrêtes de 1 à 4. Pour chaque ledstrip on numérote les leds de 0 à 26.

Allumer une LED se fait donc en 5 dimensions: Face, X, Y, LED-Strip, LED et deux valeurs différentes représentent la même LED. Si c'est pratique, c'est loin d'être simple, e.g. le système est non-bijectif.

Est-il possible d'avoir une fonction 5D -> 1D ? `f(Face, X, Y, LED-strip, LED: int) -> int` et vice-versa `f'(id: int) -> (Face, X, Y, LED-strip, LED: int)` ?
